import { createContext, useContext, useState } from 'react';

export const translations = {
  en: {
    nav_home: 'Home', nav_predict: 'Predict Rent', nav_history: 'History', nav_about: 'About',
    nav_subtitle: 'Gasabo District, Kigali',
    hero_title: 'House Rent Price Prediction', hero_subtitle: 'Using Machine Learning',
    hero_case: 'Case Study of Gasabo District, Kigali — Rwanda',
    hero_desc: 'AI-powered rent estimates for all 15 sectors of Gasabo District. Built on real Rwanda housing data with transparent, explainable predictions.',
    hero_cta: 'Get Rent Estimate', hero_how: 'How It Works',
    stat_accuracy: 'Model Accuracy', stat_sectors: 'Sectors Covered', stat_types: 'Property Types', stat_source: 'Data Source',
    features_title: 'Why Use This System?', features_sub: 'Transparent, data-driven rent estimates built specifically for the Kigali housing market.',
    feat1_title: 'XGBoost ML Model', feat1_desc: 'Trained on Gasabo District housing data with 96.6% accuracy (R² = 0.966). Reliable estimates for all 15 sectors.',
    feat2_title: 'Explainable AI (SHAP)', feat2_desc: 'Every prediction comes with SHAP values showing exactly which property features drive the rent price.',
    feat3_title: 'Dual Currency Output', feat3_desc: 'Results in both Rwandan Francs (RWF) and US Dollars (USD) with a confidence interval range.',
    feat4_title: 'Prediction History', feat4_desc: 'All predictions are saved and searchable. Track market trends and export data for analysis.',
    how_title: 'How It Works', how_sub: 'Four simple steps to get your rent estimate',
    step1_title: 'Enter Property Details', step1_desc: 'Fill in location, size, materials and amenities across 4 simple steps.',
    step2_title: 'AI Processes Features', step2_desc: 'Our XGBoost ensemble model analyzes 18 key property characteristics.',
    step3_title: 'Receive Prediction', step3_desc: 'Get an estimated monthly rent in RWF and USD with a confidence range.',
    step4_title: 'Review Explanations', step4_desc: 'SHAP values reveal the top factors influencing the predicted price.',
    sectors_title: 'All 15 Gasabo Sectors', sectors_sub: 'Full coverage — from urban Kacyiru to rural Rutunga',
    cta_title: 'Ready to estimate your rent?', cta_sub: 'Get an AI-powered rent prediction for any property in Gasabo District in under a minute.', cta_btn: 'Start Prediction',
    footer_built: 'House Rent Price Prediction · Gasabo District, Kigali', footer_dev: 'Developed by IZABAYO Honorine',
    status_checking: 'Checking model status...', status_online: 'Model Online — R² 96.6%', status_offline: 'Model Offline',
    predict_title: 'Predict House Rent', predict_sub: 'Fill in the property details below to get an AI-powered rent estimate for Gasabo District',
    result_title: 'Rent Prediction Result', result_sub: 'Based on your property details in Gasabo District',
    result_monthly: 'Estimated Monthly Rent', result_confidence: 'Confidence Range',
    result_confidence_note: 'The actual market rent is likely to fall within this range',
    result_factors: 'Price Influencing Factors', result_model: 'Model', result_accuracy: 'Accuracy (R²)', result_id: 'Prediction ID',
    btn_new: 'New Prediction', step_location: 'Location', step_property: 'Property', step_construction: 'Construction', step_amenities: 'Amenities',
    form_step: 'Step', form_of: 'of', btn_back: 'Back', btn_next: 'Next', btn_predict: 'Get Prediction', btn_predicting: 'Predicting...',
    f_district: 'District', f_sector: 'Sector', f_area_class: 'Area Classification', f_distance: 'Distance to CBD (km)',
    f_near_cbd: 'Near Kigali CBD (within 3km)', f_house_type: 'House Type', f_bedrooms: 'Bedrooms', f_total_rooms: 'Total Rooms',
    f_floor_area: 'Floor Area (m²)', f_wall: 'Wall Material', f_floor: 'Floor Material', f_roof: 'Roof Material',
    f_electricity: 'Electricity', f_water: 'Piped Water', f_toilet: 'Indoor Toilet', f_kitchen: 'Kitchen', f_parking: 'Parking Space', f_road: 'Road Access', f_select: 'Select',
    loc_title: 'Location Details', loc_sub: "Select the property's location in Gasabo District",
    prop_title: 'Property Details', prop_sub: 'Describe the size and type of the property',
    const_title: 'Construction Materials', const_sub: 'Select the building materials used',
    amen_title: 'Amenities & Access', amen_sub: 'Select available utilities and road access',
    hist_title: 'Prediction History', hist_sub: 'predictions recorded', hist_empty_title: 'No predictions yet',
    hist_empty_sub: 'Make your first prediction to see it here', hist_make: 'Make a Prediction', hist_refresh: 'Refresh',
    hist_location: 'Location', hist_property: 'Property', hist_rent: 'Predicted Rent', hist_tier: 'Tier', hist_date: 'Date',
    about_title: 'About This System', about_sub: "An AI-powered rent prediction system built specifically for Gasabo District, Kigali — Rwanda's most urbanised district with 15 diverse sectors.",
    about_mission_title: 'Mission', about_mission: 'To provide transparent, accurate, and accessible house rent predictions for Rwanda using explainable AI. We help tenants, landlords, and property developers make informed decisions with data-driven insights.',
    about_how_title: 'How It Works',
    about_data_title: 'Data Collection', about_data: 'Housing data sourced from EICV5 government surveys and NISR statistics, calibrated to real Rwanda housing market patterns across all 15 sectors of Gasabo District.',
    about_ml_title: 'Machine Learning', about_ml: 'An XGBoost ensemble model trained on 18 property features achieves R² = 0.885 accuracy through cross-validation and hyperparameter tuning.',
    about_shap_title: 'SHAP Explanations', about_shap: 'Every prediction includes SHAP values showing exactly which features influenced the price and by how much — complete transparency, no black box.',
    about_tech_title: 'Technology Stack', about_sectors_title: 'Gasabo District — All 15 Sectors',
    about_sectors_note: 'Coverage spans urban (Kacyiru, Remera), peri-urban (Kimironko, Gisozi), and rural (Rutunga, Nduba) areas.',
  },
  fr: {
    nav_home: 'Accueil', nav_predict: 'Prédire le Loyer', nav_history: 'Historique', nav_about: 'À Propos',
    nav_subtitle: 'District de Gasabo, Kigali',
    hero_title: 'Prédiction du Prix de Location', hero_subtitle: 'Par Apprentissage Automatique',
    hero_case: 'Étude de Cas du District de Gasabo, Kigali — Rwanda',
    hero_desc: "Estimations de loyer basées sur l'IA pour les 15 secteurs du District de Gasabo. Construit sur des données immobilières rwandaises réelles avec des prédictions transparentes.",
    hero_cta: 'Obtenir une Estimation', hero_how: 'Comment ça Marche',
    stat_accuracy: 'Précision du Modèle', stat_sectors: 'Secteurs Couverts', stat_types: 'Types de Propriété', stat_source: 'Source de Données',
    features_title: 'Pourquoi Utiliser ce Système?', features_sub: "Estimations de loyer transparentes pour le marché immobilier de Kigali.",
    feat1_title: 'Modèle ML XGBoost', feat1_desc: 'Entraîné sur les données de Gasabo avec 88,5% de précision (R² = 0,885).',
    feat2_title: 'IA Explicable (SHAP)', feat2_desc: 'Chaque prédiction inclut des valeurs SHAP montrant quelles caractéristiques influencent le loyer.',
    feat3_title: 'Double Devise', feat3_desc: 'Résultats en Francs Rwandais (RWF) et en Dollars US (USD) avec intervalle de confiance.',
    feat4_title: 'Historique des Prédictions', feat4_desc: 'Toutes les prédictions sont sauvegardées et consultables.',
    how_title: 'Comment ça Marche', how_sub: 'Quatre étapes simples pour obtenir votre estimation de loyer',
    step1_title: 'Entrer les Détails', step1_desc: 'Remplissez la localisation, la taille, les matériaux et les commodités.',
    step2_title: "L'IA Analyse", step2_desc: 'Notre modèle XGBoost analyse 18 caractéristiques clés de la propriété.',
    step3_title: 'Recevoir la Prédiction', step3_desc: 'Obtenez un loyer mensuel estimé en RWF et USD avec une plage de confiance.',
    step4_title: 'Revoir les Explications', step4_desc: 'Les valeurs SHAP révèlent les principaux facteurs influençant le prix prédit.',
    sectors_title: 'Les 15 Secteurs de Gasabo', sectors_sub: 'Couverture complète — de Kacyiru urbain à Rutunga rural',
    cta_title: 'Prêt à estimer votre loyer?', cta_sub: "Obtenez une prédiction de loyer pour toute propriété dans le District de Gasabo en moins d'une minute.", cta_btn: 'Commencer',
    footer_built: 'Prédiction du Prix de Location · District de Gasabo, Kigali', footer_dev: 'Développé par IZABAYO Honorine',
    status_checking: 'Vérification du modèle...', status_online: 'Modèle en Ligne — R² 0,885', status_offline: 'Modèle Hors Ligne',
    predict_title: 'Prédire le Loyer', predict_sub: 'Remplissez les détails de la propriété pour obtenir une estimation de loyer',
    result_title: 'Résultat de la Prédiction', result_sub: 'Basé sur les détails de votre propriété dans le District de Gasabo',
    result_monthly: 'Loyer Mensuel Estimé', result_confidence: 'Plage de Confiance',
    result_confidence_note: 'Le loyer réel du marché est susceptible de se situer dans cette plage',
    result_factors: 'Facteurs Influençant le Prix', result_model: 'Modèle', result_accuracy: 'Précision (R²)', result_id: 'ID de Prédiction',
    btn_new: 'Nouvelle Prédiction', step_location: 'Localisation', step_property: 'Propriété', step_construction: 'Construction', step_amenities: 'Commodités',
    form_step: 'Étape', form_of: 'sur', btn_back: 'Retour', btn_next: 'Suivant', btn_predict: 'Obtenir la Prédiction', btn_predicting: 'Prédiction...',
    f_district: 'District', f_sector: 'Secteur', f_area_class: 'Classification de Zone', f_distance: 'Distance au CBD (km)',
    f_near_cbd: 'Près du CBD de Kigali (moins de 3km)', f_house_type: 'Type de Maison', f_bedrooms: 'Chambres', f_total_rooms: 'Pièces Totales',
    f_floor_area: 'Surface au Sol (m²)', f_wall: 'Matériau des Murs', f_floor: 'Matériau du Sol', f_roof: 'Matériau du Toit',
    f_electricity: 'Électricité', f_water: 'Eau Courante', f_toilet: 'Toilettes Intérieures', f_kitchen: 'Cuisine', f_parking: 'Parking', f_road: 'Accès Routier', f_select: 'Sélectionner',
    loc_title: 'Détails de Localisation', loc_sub: 'Sélectionnez la localisation de la propriété dans le District de Gasabo',
    prop_title: 'Détails de la Propriété', prop_sub: 'Décrivez la taille et le type de la propriété',
    const_title: 'Matériaux de Construction', const_sub: 'Sélectionnez les matériaux de construction utilisés',
    amen_title: 'Commodités et Accès', amen_sub: "Sélectionnez les services disponibles et l'accès routier",
    hist_title: 'Historique des Prédictions', hist_sub: 'prédictions enregistrées', hist_empty_title: 'Aucune prédiction encore',
    hist_empty_sub: 'Faites votre première prédiction pour la voir ici', hist_make: 'Faire une Prédiction', hist_refresh: 'Actualiser',
    hist_location: 'Localisation', hist_property: 'Propriété', hist_rent: 'Loyer Prédit', hist_tier: 'Catégorie', hist_date: 'Date',
    about_title: 'À Propos du Système', about_sub: "Un système de prédiction de loyer basé sur l'IA pour le District de Gasabo, Kigali.",
    about_mission_title: 'Mission', about_mission: "Fournir des prédictions de loyer transparentes et précises pour le Rwanda en utilisant l'IA explicable.",
    about_how_title: 'Comment ça Marche',
    about_data_title: 'Collecte de Données', about_data: 'Données immobilières provenant des enquêtes gouvernementales EICV5 et des statistiques NISR.',
    about_ml_title: 'Apprentissage Automatique', about_ml: 'Un modèle XGBoost entraîné sur 18 caractéristiques atteint R² = 0,885.',
    about_shap_title: 'Explications SHAP', about_shap: 'Chaque prédiction inclut des valeurs SHAP montrant quelles caractéristiques ont influencé le prix.',
    about_tech_title: 'Stack Technologique', about_sectors_title: 'District de Gasabo — Les 15 Secteurs',
    about_sectors_note: 'Couverture des zones urbaines (Kacyiru, Remera), péri-urbaines (Kimironko) et rurales (Rutunga).',
  },
  rw: {
    nav_home: 'Ahabanza', nav_predict: "Baza Igiciro cy'Ubukode", nav_history: 'Amateka', nav_about: 'Ibyerekeye',
    nav_subtitle: 'Akarere ka Gasabo, Kigali',
    hero_title: "Guhanura Igiciro cy'Ubukode", hero_subtitle: 'Hakoreshejwe Ubwenge Bwa Mudasobwa',
    hero_case: 'Icyitegererezo cy\'Akarere ka Gasabo, Kigali — Rwanda',
    hero_desc: "Igiciro cy'ubukode gishingiye kuri AI ku masegimenti 15 yose ya Gasabo. Gushingiye ku makuru y'imitungo Rwanda.",
    hero_cta: 'Baza Igiciro', hero_how: 'Uburyo Bikora',
    stat_accuracy: 'Inenge ya Modeli', stat_sectors: 'Imasegimenti Yirenganye', stat_types: "Ubwoko bw'Inzu", stat_source: "Inkomoko y'Amakuru",
    features_title: 'Kuki Gukoresha Iri Sisitemu?', features_sub: "Igiciro cy'ubukode gishingiye ku makuru yubatswe ku isoko ry'imitungo ya Kigali.",
    feat1_title: 'Modeli ya XGBoost ML', feat1_desc: "Yigishijwe ku makuru y'imitungo ya Gasabo hamwe n'inenge ya 88.5% (R² = 0.885).",
    feat2_title: 'AI Isobanutse (SHAP)', feat2_desc: "Buri hanura rigaragaza uburyo ibintu by'imitungo bigira ingaruka ku giciro.",
    feat3_title: 'Ifaranga Ebyiri', feat3_desc: "Ibisubizo mu Francs y'u Rwanda (RWF) no mu Dolar y'Amerika (USD).",
    feat4_title: "Amateka y'Ibihanuro", feat4_desc: "Ibihanuro byose birabikwa kandi bishakwa.",
    how_title: 'Uburyo Bikora', how_sub: 'Intambwe enye zoroshye kugira ngo ubone igiciro',
    step1_title: 'Injiza Amakuru', step1_desc: 'Uzuza aho inzu iri, ingano, ibikoresho n\'ibikorwa mu ntambwe 4.',
    step2_title: 'AI Isesengura', step2_desc: 'Modeli yacu ya XGBoost isesengura ibintu 18.',
    step3_title: 'Bona Igisubizo', step3_desc: 'Bona igiciro cy\'ubukode buri kwezi mu RWF no mu USD.',
    step4_title: 'Reba Ibisobanuro', step4_desc: 'Agaciro ka SHAP kagaragaza impamvu z\'igiciro giteganijwe.',
    sectors_title: 'Imasegimenti 15 ya Gasabo', sectors_sub: 'Kurikirwa kwose — kuva Kacyiru ya murwa kugeza Rutunga ya cyaro',
    cta_title: "Witeguye kubaza igiciro cy'ubukode?", cta_sub: 'Bona ihanuro ry\'ubukode rishingiye kuri AI ku mutungo uwo ari wo wose muri Gasabo.', cta_btn: 'Tangira',
    footer_built: "Guhanura Igiciro cy'Ubukode · Akarere ka Gasabo, Kigali", footer_dev: 'Yakozwe na IZABAYO Honorine',
    status_checking: 'Gusuzuma modeli...', status_online: 'Modeli Irakora — R² 0.885', status_offline: 'Modeli Ntikora',
    predict_title: "Baza Igiciro cy'Ubukode", predict_sub: "Uzuza amakuru y'imitungo hepfo kugira ngo ubone igiciro cy'ubukode",
    result_title: "Igisubizo cy'Ihanuro", result_sub: "Gushingiye ku makuru y'imitungo yawe muri Gasabo",
    result_monthly: "Igiciro cy'Ubukode buri Kwezi", result_confidence: "Urwego rw'Icyizere",
    result_confidence_note: "Igiciro cy'isoko nyacyo gishobora kuba muri uru rwego",
    result_factors: 'Impamvu Zigira Ingaruka ku Giciro', result_model: 'Modeli', result_accuracy: 'Inenge (R²)', result_id: "Indangamuntu y'Ihanuro",
    btn_new: 'Ihanuro Rishya', step_location: 'Aho Inzu Iri', step_property: 'Imitungo', step_construction: 'Ubwubatsi', step_amenities: 'Ibikorwa',
    form_step: 'Intambwe', form_of: 'kuri', btn_back: 'Subira Inyuma', btn_next: 'Komeza', btn_predict: 'Baza Igiciro', btn_predicting: 'Biragenda...',
    f_district: 'Akarere', f_sector: 'Umurenge', f_area_class: "Ubwoko bw'Akarere", f_distance: 'Intera kuri CBD (km)',
    f_near_cbd: 'Hafi ya CBD ya Kigali (munsi ya 3km)', f_house_type: "Ubwoko bw'Inzu", f_bedrooms: 'Ibyumba byo Kuryama', f_total_rooms: 'Ibyumba Byose',
    f_floor_area: "Ubuso bw'Inzu (m²)", f_wall: "Ibikoresho by'Inzitiro", f_floor: "Ibikoresho by'Hasi", f_roof: "Ibikoresho by'Igisenge",
    f_electricity: 'Amashanyarazi', f_water: "Amazi y'Umuyoboro", f_toilet: 'Ubwiherero bwo Mu Nzu', f_kitchen: 'Igikoni', f_parking: 'Parking', f_road: 'Uburyo bwo Kugera', f_select: 'Hitamo',
    loc_title: "Amakuru y'Aho Inzu Iri", loc_sub: 'Hitamo aho imitungo iri muri Gasabo',
    prop_title: "Amakuru y'Imitungo", prop_sub: "Sobanura ingano n'ubwoko bw'imitungo",
    const_title: "Ibikoresho by'Ubwubatsi", const_sub: 'Hitamo ibikoresho by\'ubwubatsi byakoreshejwe',
    amen_title: 'Ibikorwa n\'Uburyo bwo Kugera', amen_sub: 'Hitamo serivisi zihari n\'uburyo bwo kugera',
    hist_title: "Amateka y'Ibihanuro", hist_sub: 'ibihanuro byanditswe', hist_empty_title: 'Nta bihanuro naramwe',
    hist_empty_sub: 'Kora ihanuro rya mbere kugira ngo uribone hano', hist_make: 'Kora Ihanuro', hist_refresh: 'Vugurura',
    hist_location: 'Aho Inzu Iri', hist_property: 'Imitungo', hist_rent: 'Ubukode Bwateganijwe', hist_tier: 'Icyiciro', hist_date: 'Itariki',
    about_title: 'Ibyerekeye Iri Sisitemu', about_sub: 'Sisitemu yo guhanura igiciro cy\'ubukode ishingiye kuri AI yubatswe ku buryo bwihariye kuri Gasabo.',
    about_mission_title: 'Intego', about_mission: 'Gutanga ibihanuro by\'ubukode bisobanutse kandi binoze ku Rwanda hakoreshejwe AI isobanutse.',
    about_how_title: 'Uburyo Bikora',
    about_data_title: 'Gukusanya Amakuru', about_data: "Amakuru y'imitungo avuye mu bushakashatsi bwa leta EICV5 na NISR.",
    about_ml_title: 'Kwiga kwa Mudasobwa', about_ml: 'Modeli ya XGBoost yigishijwe ku bintu 18 igera kuri R² = 0.885.',
    about_shap_title: 'Ibisobanuro bya SHAP', about_shap: 'Buri hanuro rigaragaza uburyo ibintu bigira ingaruka ku giciro.',
    about_tech_title: 'Ikoranabuhanga Ryakoreshejwe', about_sectors_title: 'Akarere ka Gasabo — Imasegimenti 15',
    about_sectors_note: 'Kurikirwa kw\'akarere ka murwa (Kacyiru, Remera), hagati (Kimironko) n\'icyaro (Rutunga).',
  },
};

const AppContext = createContext();

export function AppProvider({ children }) {
  const [theme, setTheme] = useState('light');
  const [lang, setLang] = useState('en');
  const t = (key) => translations[lang]?.[key] ?? translations.en[key] ?? key;
  const toggleTheme = () => setTheme((p) => (p === 'light' ? 'dark' : 'light'));
  return (
    <AppContext.Provider value={{ theme, toggleTheme, lang, setLang, t }}>
      <div className={theme === 'dark' ? 'dark' : ''}>{children}</div>
    </AppContext.Provider>
  );
}

export const useApp = () => useContext(AppContext);
